### ISSUE TITLE
GT.txt file

### ISSUE THREAD

**Issue by setarekhosravi** [UAVSwarm/UAVSwarm-dataset#5]
Hello, thank you for your great work I can't understand the format of the gt.txt file, especially 2 first numbers, I think it is in the format of the MOT16 challenge. Is it true?

**Comment by UAVSwarm** [comment]
Hello,
For details, please refer to the introduction in this paper
https://www.mdpi.com/2072-4292/14/11/2601




发件人：Setare Khosravi ***@***.***>
发送日期：2024-07-20 13:36:15
收件人：UAVSwarm/UAVSwarm-dataset ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[UAVSwarm/UAVSwarm-dataset] GT.txt file (Issue #5)

Hello, thank you for your great work I can't understand the format of the gt.txt file, especially 2 first numbers, I think it is in the format of the MOT16 challenge. Is it true?

**Comment by setarekhosravi** [comment]
@UAVSwarm 
Hello Again I have another question, I want to know the FPS of recorded videos for the dataset, before converting them to image sequences.
Thank you.

**Comment by setarekhosravi** [comment]
@UAVSwarm  I understand it was 30 fps.
